### ISSUE TITLE
Number are not reset when exiting the text box

### ISSUE THREAD

**Issue by BoBer78** [CarlosNZ/json-edit-react#184]
**Describe the bug**
When editing an number, it does not reset when clicking elsewhere. The internal state is unchanged but what is displayed is. 

**Expected behavior**
See below screen recording. First behavior with numbers is incorrect. Second with strings is correct. 

**Screenshots**
https://github.com/user-attachments/assets/4afc8f9b-03e1-49b6-a174-5c4efa3a7295

**Online demo**
The screen recording was made using the live demo. 

Thanks for the great package by the way, very intuitive and super useful !

**Comment by CarlosNZ** [comment]
Thanks for spotting this inconsistency, I'll fix ASAP!

**Comment by CarlosNZ** [comment]
Should be fixed now in v1.25.1.

Thanks for reporting -- it was literally a one word error (just referring to the wrong variable), but it could have gone unnoticed for a long time!

**Comment by BoBer78** [comment]
Sorry to bother again, it seems like the issue is still unresolved. I tried locally and in the live demo on version v1.25.1. 

Just to be clear, here are the steps to recreate : 
- click on a number (for example the `99` in the demo)
- Enter a random value (valid one)
- Click on another field. 

--> This will leave the number you entered shown on screen. It does not trigger validation nor sets the internal state. All the other field types (for example strings) are reset to their old value when you repeat the same steps. 

This is not an urgent fix for us, just letting you know that the bug is still there.

**Comment by CarlosNZ** [comment]
Oh, that's annoying. At first I was unable to reproduce it on the demo, but I did it a few more times and eventually it happened. Damn, must be a race condition somewhere -- I'll have a closer look into it.

**Comment by CarlosNZ** [comment]
@BoBer78 -- hey, just wondering if you're still seeing this in the latest version?

**Comment by BoBer78** [comment]
Yes I still see the issue (locally in in the demo), I will update this comment tomorrow with some video.

**Comment by CarlosNZ** [comment]
@BoBer78 Just to let you know, in V2.0 of this component (releasing soon), the behaviour is now that *all* fields commit their entries when opening an edit in another node. The reason being: a) it's consistent with Tab behaviour (when you tab out of a value, it commits the entry), and b) this is standard practice for most user interfaces -- "click outside" usually means "keep what I've changed". 

Does this sound reasonable to you?

**Comment by CarlosNZ** [comment]
Hopefully this issue is resolved in V1. But there is a V2 beta available now which has a much more robust underlying state management so there shouldn't be any stale data being saved.
